// The SRD 5.2.1 spell list. Every spell is here so preparation / known counts
// are accurate; `build` is authored for the ones that do something in a fight.
// Class lists are a hand transcription of the SRD — spot-check before trusting
// an exotic assignment. Utility spells (no `build`) still occupy a prepared slot.

import type { Spell, SpellClass, SpellRole } from "./types";
import { atk, saveDmg, saveCond, effect, heal, conjure, cantripDice } from "./types";

const W: SpellClass = "wizard", S: SpellClass = "sorcerer", C: SpellClass = "cleric",
  D: SpellClass = "druid", B: SpellClass = "bard", K: SpellClass = "warlock",
  P: SpellClass = "paladin", R: SpellClass = "ranger", A: SpellClass = "artificer";

type Opt = {
  ct?: "action" | "bonus" | "reaction";
  conc?: boolean;
  rit?: boolean;
  role?: SpellRole;
  max?: number;
  build?: Spell["build"];
};

const S_ = (
  id: string, name: string, level: number,
  school: Spell["school"], classes: SpellClass[], o: Opt = {},
): Spell => ({
  id, name, level, school, classes,
  castTime: o.ct ?? "action",
  concentration: o.conc ?? false,
  ritual: o.rit,
  role: o.role ?? "utility",
  maxUpcast: o.max,
  build: o.build,
});

// cantrip damage that scales with character level
const cantripAtk = (die: number, dtype: Parameters<typeof saveDmg>[4]): Spell["build"] =>
  (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [
    { type: "attack", bonus: c.toHit, onHit: [{ type: "damage", amount: `${cantripDice(c.casterLevel)}d${die}`, damageType: dtype }] },
  ] }];
const cantripSave = (ability: Parameters<typeof saveCond>[0], die: number, dtype: Parameters<typeof saveDmg>[4]): Spell["build"] =>
  (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [
    { type: "save", ability, dc: c.dc, onFail: [{ type: "damage", amount: `${cantripDice(c.casterLevel)}d${die}`, damageType: dtype }] },
  ] }];

export const SPELLS: Spell[] = [
  // ─────────────────────────────── cantrips ───────────────────────────────
  S_("acid-splash", "Acid Splash", 0, "evocation", [S, W, A], { role: "damage", build: cantripSave("dex", 6, "acid") }),
  S_("chill-touch", "Chill Touch", 0, "necromancy", [S, W, K], { role: "damage", build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "attack", bonus: c.toHit, onHit: [{ type: "damage", amount: `${cantripDice(c.casterLevel)}d8`, damageType: "necrotic" }, { type: "applyEffect", name: "chill-touch", durationRounds: 1, mods: { cannotHeal: true } }] }] }] }),
  S_("dancing-lights", "Dancing Lights", 0, "illusion", [B, S, W, A], { conc: true }),
  S_("druidcraft", "Druidcraft", 0, "transmutation", [D]),
  S_("eldritch-blast", "Eldritch Blast", 0, "evocation", [K], { role: "damage", build: (c) => { const beams = c.casterLevel >= 17 ? 4 : c.casterLevel >= 11 ? 3 : c.casterLevel >= 5 ? 2 : 1; return [{ type: "target", who: { who: "aiChoice" }, effects: Array.from({ length: beams }, () => ({ type: "attack" as const, bonus: c.toHit, onHit: [{ type: "damage" as const, amount: `1d10+${c.spellMod}`, damageType: "force" as const }] })) }]; } }),
  S_("fire-bolt", "Fire Bolt", 0, "evocation", [S, W, A], { role: "damage", build: cantripAtk(10, "fire") }),
  S_("guidance", "Guidance", 0, "divination", [C, D, A], { conc: true, role: "buff" }),
  S_("light", "Light", 0, "evocation", [B, C, S, W, A]),
  S_("mage-hand", "Mage Hand", 0, "conjuration", [B, S, W, K, A]),
  S_("mending", "Mending", 0, "transmutation", [B, C, D, S, W, A]),
  S_("message", "Message", 0, "transmutation", [B, S, W, A]),
  S_("minor-illusion", "Minor Illusion", 0, "illusion", [B, S, W, K]),
  S_("poison-spray", "Poison Spray", 0, "conjuration", [D, S, W, K, A], { role: "damage", build: cantripSave("con", 12, "poison") }),
  S_("prestidigitation", "Prestidigitation", 0, "transmutation", [B, S, W, K, A]),
  S_("produce-flame", "Produce Flame", 0, "conjuration", [D], { role: "damage", build: cantripAtk(8, "fire") }),
  S_("ray-of-frost", "Ray of Frost", 0, "evocation", [S, W, A], { role: "damage", build: cantripAtk(8, "cold") }),
  S_("resistance", "Resistance", 0, "abjuration", [C, D, A], { conc: true, role: "buff" }),
  S_("sacred-flame", "Sacred Flame", 0, "evocation", [C], { role: "damage", build: cantripSave("dex", 8, "radiant") }),
  S_("shillelagh", "Shillelagh", 0, "transmutation", [D], { ct: "bonus", role: "buff" }),
  S_("shocking-grasp", "Shocking Grasp", 0, "evocation", [S, W, A], { role: "damage", build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "attack", bonus: c.toHit, onHit: [{ type: "damage", amount: `${cantripDice(c.casterLevel)}d8`, damageType: "lightning" }, { type: "applyEffect", name: "shocked", durationRounds: 1, mods: { noReactions: true } }] }] }] }),
  S_("spare-the-dying", "Spare the Dying", 0, "necromancy", [C, A], { role: "heal" }),
  S_("thaumaturgy", "Thaumaturgy", 0, "transmutation", [C]),
  S_("thorn-whip", "Thorn Whip", 0, "transmutation", [D, A], { role: "damage", build: cantripAtk(6, "piercing") }),
  S_("true-strike", "True Strike", 0, "divination", [B, S, W]),
  S_("vicious-mockery", "Vicious Mockery", 0, "enchantment", [B], { role: "damage", build: cantripSave("wis", 4, "psychic") }),
  S_("blade-ward", "Blade Ward", 0, "abjuration", [B, S, K, W]),
  S_("friends", "Friends", 0, "enchantment", [B, S, K, W], { conc: true }),

  // ─────────────────────────────── level 1 ────────────────────────────────
  S_("alarm", "Alarm", 1, "abjuration", [R, W, A], { rit: true }),
  S_("animal-friendship", "Animal Friendship", 1, "enchantment", [B, D, R]),
  S_("bane", "Bane", 1, "enchantment", [B, C], { conc: true, role: "control", build: saveCond("cha", "marked-for-reckoning", 10, { who: { who: "chosenEnemies", upTo: 3 }, saveEnds: false }) }),
  S_("bless", "Bless", 1, "enchantment", [C, P], { conc: true, role: "buff", build: effect("bless", { saveBonusAll: 2 }, { who: "eachAlly" }) }),
  S_("burning-hands", "Burning Hands", 1, "evocation", [S, W], { role: "damage", max: 9, build: saveDmg(1, "dex", 3, 6, "fire", 1, { who: "area", shape: "cone", size: 15 }) }),
  S_("charm-person", "Charm Person", 1, "enchantment", [B, D, S, W, K], { role: "control", max: 5, build: saveCond("wis", "charmed", 10, { saveEnds: true }) }),
  S_("color-spray", "Color Spray", 1, "illusion", [S, W], { role: "control", build: saveCond("con", "blinded", 1, { who: { who: "chosenEnemies", upTo: 3 } }) }),
  S_("command", "Command", 1, "enchantment", [C, P], { role: "control", max: 5, build: saveCond("wis", "incapacitated", 1, { perSlotTargets: 1, targetsAtLevel: 1, spellLevel: 1 }) }),
  S_("comprehend-languages", "Comprehend Languages", 1, "divination", [B, S, W, K], { rit: true }),
  S_("create-or-destroy-water", "Create or Destroy Water", 1, "transmutation", [C, D]),
  S_("cure-wounds", "Cure Wounds", 1, "evocation", [B, C, D, P, R, A], { role: "heal", max: 9, build: heal(1, 1, 8, 1) }),
  S_("detect-evil-and-good", "Detect Evil and Good", 1, "divination", [C, P], { conc: true }),
  S_("detect-magic", "Detect Magic", 1, "divination", [B, C, D, P, R, S, W, A], { conc: true, rit: true }),
  S_("detect-poison-and-disease", "Detect Poison and Disease", 1, "divination", [C, D, P, R, A], { conc: true, rit: true }),
  S_("disguise-self", "Disguise Self", 1, "illusion", [B, S, W, A]),
  S_("divine-favor", "Divine Favor", 1, "evocation", [P], { conc: true, ct: "bonus", role: "buff", build: effect("divine-favor", {}, { who: "self" }) }),
  S_("entangle", "Entangle", 1, "conjuration", [D], { conc: true, role: "control", build: saveCond("str", "restrained", 10, { who: { who: "chosenEnemies", upTo: 3 }, saveEnds: true }) }),
  S_("expeditious-retreat", "Expeditious Retreat", 1, "transmutation", [S, W, K, A], { conc: true, ct: "bonus" }),
  S_("faerie-fire", "Faerie Fire", 1, "evocation", [B, D, A], { conc: true, role: "control", build: (c) => [{ type: "target", who: { who: "chosenEnemies", upTo: 3 }, effects: [{ type: "save", ability: "dex", dc: c.dc, onFail: [{ type: "applyEffect", name: "faerie-fire", durationRounds: 10, mods: { attacksAgainstItAdvantage: "adv" } }] }] }] }),
  S_("false-life", "False Life", 1, "necromancy", [S, W, A], { role: "buff", build: (c) => [{ type: "target", who: { who: "self" }, effects: [{ type: "tempHp", amount: `1d4+${3 + Math.max(0, c.slotLevel - 1) * 5}` }] }] }),
  S_("feather-fall", "Feather Fall", 1, "transmutation", [B, S, W, A], { ct: "reaction" }),
  S_("find-familiar", "Find Familiar", 1, "conjuration", [W], { rit: true }),
  S_("fog-cloud", "Fog Cloud", 1, "conjuration", [D, R, S, W, A], { conc: true, role: "control" }),
  S_("grease", "Grease", 1, "conjuration", [W, A], { role: "control", build: saveCond("dex", "prone", 1, { who: { who: "chosenEnemies", upTo: 2 } }) }),
  S_("guiding-bolt", "Guiding Bolt", 1, "evocation", [C], { role: "damage", max: 9, build: (c) => { const d = 4 + Math.max(0, c.slotLevel - 1); return [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "attack", bonus: c.toHit, onHit: [{ type: "damage", amount: `${d}d6`, damageType: "radiant" }, { type: "applyEffect", name: "guiding-bolt", durationRounds: 1, mods: { attacksAgainstItAdvantage: "adv" } }] }] }]; } }),
  S_("healing-word", "Healing Word", 1, "evocation", [B, C, D], { ct: "bonus", role: "heal", max: 9, build: heal(1, 1, 4, 1) }),
  S_("heroism", "Heroism", 1, "enchantment", [B, P], { conc: true, role: "buff", build: effect("heroism", {}, { who: "self" }) }),
  S_("hex", "Hex", 1, "enchantment", [K], { conc: true, ct: "bonus", role: "buff", build: effect("hex", {}, { who: "self" }) }),
  S_("hunters-mark", "Hunter's Mark", 1, "divination", [R], { conc: true, ct: "bonus", role: "buff", build: effect("hunters-mark", {}, { who: "self" }) }),
  S_("identify", "Identify", 1, "divination", [B, W, A], { rit: true }),
  S_("inflict-wounds", "Inflict Wounds", 1, "necromancy", [C], { role: "damage", max: 9, build: (c) => { const d = 3 + Math.max(0, c.slotLevel - 1); return [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "attack", bonus: c.toHit, onHit: [{ type: "damage", amount: `${d}d10`, damageType: "necrotic" }] }] }]; } }),
  S_("jump", "Jump", 1, "transmutation", [D, R, S, W, A]),
  S_("longstrider", "Longstrider", 1, "transmutation", [B, D, R, W, A]),
  S_("mage-armor", "Mage Armor", 1, "abjuration", [S, W], { role: "buff", build: effect("mage-armor", { acBonus: 3 }, { who: "self" }) }),
  S_("magic-missile", "Magic Missile", 1, "evocation", [S, W], { role: "damage", max: 9, build: (c) => { const darts = 3 + Math.max(0, c.slotLevel - 1); return [{ type: "target", who: { who: "aiChoice" }, effects: Array.from({ length: darts }, () => ({ type: "damage" as const, amount: "1d4+1", damageType: "force" as const })) }]; } }),
  S_("protection-from-evil-and-good", "Protection from Evil and Good", 1, "abjuration", [C, D, P, W, K, A], { conc: true, role: "defense", build: effect("prot-evil-good", { attacksAgainstItAdvantage: "dis" }, { who: "self" }) }),
  S_("purify-food-and-drink", "Purify Food and Drink", 1, "transmutation", [C, D, P, A], { rit: true }),
  S_("ray-of-sickness", "Ray of Sickness", 1, "necromancy", [S, W], { role: "damage", max: 9, build: (c) => { const d = 2 + Math.max(0, c.slotLevel - 1); return [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "attack", bonus: c.toHit, onHit: [{ type: "damage", amount: `${d}d8`, damageType: "poison" }, { type: "save", ability: "con", dc: c.dc, onFail: [{ type: "applyCondition", condition: "poisoned", durationRounds: 1 }] }] }] }]; } }),
  S_("sanctuary", "Sanctuary", 1, "abjuration", [C, A], { ct: "bonus", role: "defense", build: effect("sanctuary", { attacksAgainstItAdvantage: "dis" }, { who: "self", durationRounds: 3 }) }),
  S_("shield", "Shield", 1, "abjuration", [S, W], { ct: "reaction", role: "defense" }),
  S_("absorb-elements", "Absorb Elements", 1, "abjuration", [S, W, D, R, A], { ct: "reaction", role: "defense" }),
  S_("hellish-rebuke", "Hellish Rebuke", 1, "evocation", [K], { ct: "reaction", role: "damage", max: 9 }),
  S_("shield-of-faith", "Shield of Faith", 1, "abjuration", [C, P], { conc: true, ct: "bonus", role: "buff", build: effect("shield-of-faith", { acBonus: 2 }, { who: "self" }) }),
  S_("silent-image", "Silent Image", 1, "illusion", [B, S, W], { conc: true }),
  S_("sleep", "Sleep", 1, "enchantment", [B, S, W], { role: "control", max: 9, build: saveCond("wis", "unconscious", 2, { who: { who: "chosenEnemies", upTo: 2 } }) }),
  S_("speak-with-animals", "Speak with Animals", 1, "divination", [B, D, R], { rit: true }),
  S_("thunderwave", "Thunderwave", 1, "evocation", [B, D, S, W, A], { role: "damage", max: 9, build: saveDmg(1, "con", 2, 8, "thunder", 1, { who: "area", shape: "cube", size: 15 }) }),
  S_("unseen-servant", "Unseen Servant", 1, "conjuration", [B, W, K, A], { rit: true }),
  S_("witch-bolt", "Witch Bolt", 1, "evocation", [S, W, K], { conc: true, role: "damage", build: atk(1, 1, 12, "lightning", 1) }),
  S_("armor-of-agathys", "Armor of Agathys", 1, "abjuration", [K], { role: "buff", max: 9, build: (c) => [{ type: "target", who: { who: "self" }, effects: [{ type: "tempHp", amount: `${5 + Math.max(0, c.slotLevel - 1) * 5}` }] }] }),
  S_("arms-of-hadar", "Arms of Hadar", 1, "conjuration", [K], { role: "damage", max: 9, build: saveDmg(1, "str", 2, 6, "necrotic", 1, { who: "area", shape: "emanation", size: 10 }) }),
  S_("chromatic-orb", "Chromatic Orb", 1, "evocation", [S, W], { role: "damage", max: 9, build: atk(1, 3, 8, "fire", 1) }),
  S_("compelled-duel", "Compelled Duel", 1, "enchantment", [P], { ct: "bonus", conc: true }),
  S_("dissonant-whispers", "Dissonant Whispers", 1, "enchantment", [B], { role: "damage", max: 9, build: saveDmg(1, "wis", 3, 6, "psychic", 1, { who: "aiChoice" }) }),
  S_("ensnaring-strike", "Ensnaring Strike", 1, "conjuration", [R], { ct: "bonus", conc: true, role: "buff", build: effect("ensnaring-strike", {}, { who: "self" }) }),
  S_("goodberry", "Goodberry", 1, "transmutation", [D, R]),
  S_("hail-of-thorns", "Hail of Thorns", 1, "conjuration", [R], { ct: "bonus", conc: true, role: "buff", build: effect("hail-of-thorns", {}, { who: "self" }) }),
  S_("ice-knife", "Ice Knife", 1, "conjuration", [D, S, W], { role: "damage", max: 9, build: (c) => { const cold = 2 + Math.max(0, c.slotLevel - 1); return [
    { type: "target", who: { who: "aiChoice" }, effects: [{ type: "attack", bonus: c.toHit, onHit: [{ type: "damage", amount: "1d10", damageType: "piercing" }] }] },
    { type: "target", who: { who: "area", shape: "sphere", size: 5 }, effects: [{ type: "save", ability: "dex", dc: c.dc, onFail: [{ type: "damage", amount: `${cold}d6`, damageType: "cold" }], onSuccess: [{ type: "damage", amount: `${cold}d6`, damageType: "cold", half: true }] }] },
  ]; } }),
  S_("illusory-script", "Illusory Script", 1, "illusion", [B, K, W], { rit: true }),
  S_("searing-smite", "Searing Smite", 1, "evocation", [P], { ct: "bonus", conc: true, role: "buff", build: effect("searing-smite", {}, { who: "self" }) }),
  S_("tashas-hideous-laughter", "Tasha's Hideous Laughter", 1, "enchantment", [B, W], { conc: true, role: "control", build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "save", ability: "wis", dc: c.dc, onFail: [
    { type: "applyCondition", condition: "prone", durationRounds: 10, saveEnds: { ability: "wis", dc: c.dc, at: "endOfTurn" } },
    { type: "applyCondition", condition: "incapacitated", durationRounds: 10, saveEnds: { ability: "wis", dc: c.dc, at: "endOfTurn" } },
  ] }] }] }),
  S_("tensers-floating-disk", "Tenser's Floating Disk", 1, "conjuration", [W], { rit: true }),
  S_("thunderous-smite", "Thunderous Smite", 1, "evocation", [P], { ct: "bonus", conc: true, role: "buff", build: effect("thunderous-smite", {}, { who: "self" }) }),
  S_("wrathful-smite", "Wrathful Smite", 1, "evocation", [P], { ct: "bonus", conc: true, role: "buff", build: effect("wrathful-smite", {}, { who: "self" }) }),

  // ─────────────────────────────── level 2 ────────────────────────────────
  S_("aid", "Aid", 2, "abjuration", [C, P, A], { role: "buff", max: 9, build: (c) => [{ type: "target", who: { who: "eachAlly" }, effects: [{ type: "tempHp", amount: `${5 + Math.max(0, c.slotLevel - 2) * 5}` }] }] }),  // approximates the max-HP bump
  S_("alter-self", "Alter Self", 2, "transmutation", [S, W, A], { conc: true }),
  S_("animal-messenger", "Animal Messenger", 2, "enchantment", [B, D, R], { rit: true }),
  S_("arcane-lock", "Arcane Lock", 2, "abjuration", [W, A]),
  S_("augury", "Augury", 2, "divination", [C, A], { rit: true }),
  S_("barkskin", "Barkskin", 2, "transmutation", [D, R, A], { role: "buff", build: effect("barkskin", { acBonus: 1 }, { who: "self" }) }),
  S_("blindness-deafness", "Blindness/Deafness", 2, "transmutation", [B, C, S, W], { role: "control", max: 9, build: saveCond("con", "blinded", 10, { saveEnds: true, perSlotTargets: 1, targetsAtLevel: 2, spellLevel: 2 }) }),
  S_("blur", "Blur", 2, "illusion", [S, W, A], { conc: true, role: "defense", build: effect("blur", { attacksAgainstItAdvantage: "dis" }, { who: "self" }) }),
  S_("branding-smite", "Branding Smite", 2, "evocation", [P], { conc: true, ct: "bonus", role: "buff", build: effect("branding-smite", {}, { who: "self" }) }),
  S_("calm-emotions", "Calm Emotions", 2, "enchantment", [B, C], { conc: true, role: "control", build: saveCond("cha", "charmed", 3, { who: { who: "chosenEnemies", upTo: 3 } }) }),
  S_("continual-flame", "Continual Flame", 2, "evocation", [C, W, A]),
  S_("darkness", "Darkness", 2, "evocation", [S, W, K], { conc: true, role: "control" }),
  S_("darkvision", "Darkvision", 2, "transmutation", [D, R, S, W, A]),
  S_("detect-thoughts", "Detect Thoughts", 2, "divination", [B, S, W], { conc: true }),
  S_("enhance-ability", "Enhance Ability", 2, "transmutation", [B, C, D, S, A], { conc: true, role: "buff" }),
  S_("enlarge-reduce", "Enlarge/Reduce", 2, "transmutation", [S, W, A], { conc: true, role: "buff", build: effect("enlarge", {}, { who: "self" }) }),
  S_("enthrall", "Enthrall", 2, "enchantment", [B, K]),
  S_("find-steed", "Find Steed", 2, "conjuration", [P]),
  S_("find-traps", "Find Traps", 2, "divination", [C, D, R]),
  S_("flame-blade", "Flame Blade", 2, "evocation", [D], { conc: true, ct: "bonus", role: "damage", build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "attack", bonus: c.toHit, onHit: [{ type: "damage", amount: `${3 + Math.floor(Math.max(0, c.slotLevel - 2) / 2) * 1}d6`, damageType: "fire" }] }] }] }),
  S_("flaming-sphere", "Flaming Sphere", 2, "conjuration", [D, W], { conc: true, role: "damage", max: 9, build: saveDmg(2, "dex", 2, 6, "fire", 1, { who: "aiChoice" }) }),
  S_("gentle-repose", "Gentle Repose", 2, "necromancy", [C, W], { rit: true }),
  S_("gust-of-wind", "Gust of Wind", 2, "evocation", [D, R, S, W, A], { conc: true, role: "control" }),
  S_("heat-metal", "Heat Metal", 2, "transmutation", [B, D, A], { conc: true, ct: "bonus", role: "damage", max: 9, build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "damage", amount: `${2 + Math.max(0, c.slotLevel - 2)}d8`, damageType: "fire" }] }] }),
  S_("hold-person", "Hold Person", 2, "enchantment", [B, C, D, S, W, K], { conc: true, role: "control", max: 9, build: saveCond("wis", "paralyzed", 10, { saveEnds: true, perSlotTargets: 1, targetsAtLevel: 2, spellLevel: 2 }) }),
  S_("invisibility", "Invisibility", 2, "illusion", [B, S, W, K, A], { conc: true, role: "buff", build: effect("invisible", { attacksAgainstItAdvantage: "dis" }, { who: "self" }) }),
  S_("knock", "Knock", 2, "transmutation", [B, S, W]),
  S_("lesser-restoration", "Lesser Restoration", 2, "abjuration", [B, C, D, P, R, A], { role: "heal" }),
  S_("levitate", "Levitate", 2, "transmutation", [S, W, A], { conc: true }),
  S_("locate-animals-or-plants", "Locate Animals or Plants", 2, "divination", [B, D, R], { rit: true }),
  S_("locate-object", "Locate Object", 2, "divination", [B, C, D, P, R, W, A], { conc: true }),
  S_("magic-mouth", "Magic Mouth", 2, "illusion", [B, W, A], { rit: true }),
  S_("magic-weapon", "Magic Weapon", 2, "transmutation", [P, W, A], { conc: true, ct: "bonus", role: "buff" }),
  S_("mirror-image", "Mirror Image", 2, "illusion", [S, W, K], { role: "defense", build: effect("mirror-image", { attacksAgainstItAdvantage: "dis" }, { who: "self", durationRounds: 10 }) }),
  S_("misty-step", "Misty Step", 2, "conjuration", [S, W, K], { ct: "bonus", role: "defense", build: () => [{ type: "move", kind: "teleportSelf", distance: 30 }] }),
  S_("moonbeam", "Moonbeam", 2, "evocation", [D], { conc: true, role: "damage", max: 9, build: saveDmg(2, "con", 2, 10, "radiant", 1, { who: "aiChoice" }) }),
  S_("pass-without-trace", "Pass Without Trace", 2, "abjuration", [D, R], { conc: true }),
  S_("prayer-of-healing", "Prayer of Healing", 2, "evocation", [C], { role: "utility" }),  // 10-minute cast — out of combat only
  S_("protection-from-poison", "Protection from Poison", 2, "abjuration", [C, D, P, R, A], { role: "defense" }),
  S_("ray-of-enfeeblement", "Ray of Enfeeblement", 2, "necromancy", [W, K], { conc: true, role: "control", build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "attack", bonus: c.toHit, onHit: [{ type: "applyEffect", name: "enfeebled", durationRounds: 10, mods: { attackAdvantage: "dis" }, saveEnds: { ability: "con", dc: c.dc, at: "endOfTurn" } }] }] }] }),
  S_("rope-trick", "Rope Trick", 2, "transmutation", [W, A]),
  S_("scorching-ray", "Scorching Ray", 2, "evocation", [S, W], { role: "damage", max: 9, build: (c) => { const rays = 3 + Math.max(0, c.slotLevel - 2); return [{ type: "target", who: { who: "aiChoice" }, effects: Array.from({ length: rays }, () => ({ type: "attack" as const, bonus: c.toHit, onHit: [{ type: "damage" as const, amount: "2d6", damageType: "fire" as const }] })) }]; } }),
  S_("see-invisibility", "See Invisibility", 2, "divination", [B, S, W, A]),
  S_("shatter", "Shatter", 2, "evocation", [B, S, W, K], { role: "damage", max: 9, build: saveDmg(2, "con", 3, 8, "thunder", 1) }),
  S_("silence", "Silence", 2, "illusion", [B, C, R], { conc: true, rit: true, role: "control" }),
  S_("spider-climb", "Spider Climb", 2, "transmutation", [S, W, K, A], { conc: true }),
  S_("spike-growth", "Spike Growth", 2, "transmutation", [D, R], { conc: true, role: "control", build: () => [{ type: "target", who: { who: "eachEnemy" }, effects: [{ type: "applyEffect", name: "spike-growth", durationRounds: 10, mods: { speedZero: false }, tick: [{ type: "damage", amount: "2d4", damageType: "piercing" }] }] }] }),
  S_("spiritual-weapon", "Spiritual Weapon", 2, "evocation", [C], { ct: "bonus", role: "damage", max: 9, build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "attack", bonus: c.toHit, onHit: [{ type: "damage", amount: `${1 + Math.floor(Math.max(0, c.slotLevel - 2) / 2)}d8+${c.spellMod}`, damageType: "force" }] }] }] }),
  S_("suggestion", "Suggestion", 2, "enchantment", [B, S, W, K], { conc: true, role: "control", build: saveCond("wis", "charmed", 10, { saveEnds: false }) }),
  S_("warding-bond", "Warding Bond", 2, "abjuration", [C, A], { role: "defense" }),
  S_("web", "Web", 2, "conjuration", [S, W, A], { conc: true, role: "control", build: saveCond("dex", "restrained", 10, { who: { who: "chosenEnemies", upTo: 3 }, saveEnds: true }) }),
  S_("zone-of-truth", "Zone of Truth", 2, "enchantment", [B, C, P]),
  S_("beast-sense", "Beast Sense", 2, "divination", [D, R], { conc: true, rit: true }),
  S_("cloud-of-daggers", "Cloud of Daggers", 2, "conjuration", [B, S, K, W], { conc: true, role: "damage", max: 9, build: (c) => { const d = 4 + Math.max(0, c.slotLevel - 2) * 2; return [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "applyEffect", name: "cloud-of-daggers", durationRounds: 10, tick: [{ type: "damage", amount: `${d}d4`, damageType: "slashing" }] }] }]; } }),
  S_("cordon-of-arrows", "Cordon of Arrows", 2, "transmutation", [R]),
  S_("crown-of-madness", "Crown of Madness", 2, "enchantment", [B, S, K, W], { conc: true, role: "control", build: saveCond("wis", "charmed", 10, { who: { who: "aiChoice" }, saveEnds: true }) }),
  S_("dragons-breath", "Dragon's Breath", 2, "transmutation", [S, W], { ct: "bonus", conc: true, role: "damage", max: 9, build: saveDmg(2, "dex", 3, 6, "fire", 1, { who: "area", shape: "cone", size: 15 }) }),
  S_("melfs-acid-arrow", "Melf's Acid Arrow", 2, "evocation", [W], { role: "damage", max: 9, build: (c) => { const now = 4 + Math.max(0, c.slotLevel - 2); const later = 2 + Math.max(0, c.slotLevel - 2); return [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "attack", bonus: c.toHit, onHit: [
    { type: "damage", amount: `${now}d4`, damageType: "acid" },
    { type: "applyEffect", name: "acid-arrow-lingering", durationRounds: 1, tick: [{ type: "damage", amount: `${later}d4`, damageType: "acid" }] },
  ], onMiss: [{ type: "damage", amount: `${now}d4`, damageType: "acid", half: true }] }] }]; } }),
  S_("mind-spike", "Mind Spike", 2, "divination", [S, K, W], { conc: true, role: "damage", max: 9, build: saveDmg(2, "wis", 3, 8, "psychic", 1, { who: "aiChoice" }) }),
  S_("nystuls-magic-aura", "Nystul's Magic Aura", 2, "illusion", [W]),
  S_("phantasmal-force", "Phantasmal Force", 2, "illusion", [B, S, W], { conc: true, role: "control", build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "save", ability: "int", dc: c.dc, onFail: [{ type: "applyEffect", name: "phantasmal-force", durationRounds: 10, tick: [{ type: "damage", amount: "1d6", damageType: "psychic" }] }] }] }] }),

  // ─────────────────────────────── level 3 ────────────────────────────────
  S_("animate-dead", "Animate Dead", 3, "necromancy", [C, W], { role: "summon", max: 9, build: conjure("zombie", "2", 6) }),
  S_("aura-of-vitality", "Aura of Vitality", 3, "evocation", [P], { conc: true, ct: "bonus", role: "heal", build: () => [{ type: "target", who: { who: "lowestHpAlly" }, effects: [{ type: "heal", amount: "2d6" }] }] }),
  S_("beacon-of-hope", "Beacon of Hope", 3, "abjuration", [C], { conc: true, role: "buff", build: effect("beacon-of-hope", { saveAdvantage: "adv" }, { who: "eachAlly" }) }),
  S_("bestow-curse", "Bestow Curse", 3, "necromancy", [B, C, W], { conc: true, role: "control", max: 9, build: saveCond("wis", "incapacitated", 10, { saveEnds: false }) }),
  S_("blink", "Blink", 3, "transmutation", [S, W, A], { role: "defense", build: effect("blink", { attacksAgainstItAdvantage: "dis" }, { who: "self" }) }),
  S_("call-lightning", "Call Lightning", 3, "conjuration", [D], { conc: true, role: "damage", max: 9, build: saveDmg(3, "dex", 3, 10, "lightning", 1, { who: "aiChoice" }) }),
  S_("clairvoyance", "Clairvoyance", 3, "divination", [B, C, S, W], { conc: true }),
  S_("conjure-animals", "Conjure Animals", 3, "conjuration", [D, R], { conc: true, role: "summon", max: 9, build: (c) => [{ type: "summon", statBlock: "wolf", count: `${2 + Math.max(0, c.slotLevel - 3)}`, max: 8 }] }),
  S_("counterspell", "Counterspell", 3, "abjuration", [S, W, K, A], { ct: "reaction", role: "defense" }),
  S_("create-food-and-water", "Create Food and Water", 3, "conjuration", [C, P, A]),
  S_("daylight", "Daylight", 3, "evocation", [C, D, P, R, S, W]),
  S_("dispel-magic", "Dispel Magic", 3, "abjuration", [B, C, D, P, S, W, K, A], { role: "defense", build: () => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "removeEffect", name: "*" }] }] }),
  S_("fear", "Fear", 3, "illusion", [B, S, W, K], { conc: true, role: "control", build: saveCond("wis", "frightened", 10, { who: "area", saveEnds: true }) }),
  S_("feign-death", "Feign Death", 3, "necromancy", [B, C, D, W], { rit: true }),
  S_("fireball", "Fireball", 3, "evocation", [S, W], { role: "damage", max: 9, build: saveDmg(3, "dex", 8, 6, "fire", 1) }),
  S_("fly", "Fly", 3, "transmutation", [S, W, K, A], { conc: true, role: "buff", build: effect("fly", {}, { who: "self" }) }),
  S_("gaseous-form", "Gaseous Form", 3, "transmutation", [S, W, K], { conc: true }),
  S_("glyph-of-warding", "Glyph of Warding", 3, "abjuration", [B, C, W, A]),
  S_("haste", "Haste", 3, "transmutation", [S, W, A], { conc: true, role: "buff", build: effect("haste", { acBonus: 2 }, { who: "self" }) }),
  S_("hypnotic-pattern", "Hypnotic Pattern", 3, "illusion", [B, S, W, K], { conc: true, role: "control", build: saveCond("wis", "incapacitated", 10, { who: "area", saveEnds: true }) }),
  S_("lightning-bolt", "Lightning Bolt", 3, "evocation", [S, W], { role: "damage", max: 9, build: saveDmg(3, "dex", 8, 6, "lightning", 1, { who: "area", shape: "line", size: 100 }) }),
  S_("magic-circle", "Magic Circle", 3, "abjuration", [C, P, W, K, A]),
  S_("major-image", "Major Image", 3, "illusion", [B, S, W, K], { conc: true }),
  S_("mass-healing-word", "Mass Healing Word", 3, "evocation", [C], { ct: "bonus", role: "heal", max: 9, build: (c) => [{ type: "target", who: { who: "eachAlly" }, effects: [{ type: "heal", amount: `${1 + Math.max(0, c.slotLevel - 3)}d4+${c.spellMod}` }] }] }),
  S_("meld-into-stone", "Meld into Stone", 3, "transmutation", [C, D], { rit: true }),
  S_("nondetection", "Nondetection", 3, "abjuration", [B, R, W, A]),
  S_("phantom-steed", "Phantom Steed", 3, "illusion", [W], { rit: true }),
  S_("plant-growth", "Plant Growth", 3, "transmutation", [B, D, R]),
  S_("protection-from-energy", "Protection from Energy", 3, "abjuration", [C, D, R, S, W, A], { conc: true, role: "defense", build: effect("prot-energy", { damageTakenMultiplier: 0.6 }, { who: "self" }) }),
  S_("remove-curse", "Remove Curse", 3, "abjuration", [C, P, W, K]),
  S_("revivify", "Revivify", 3, "necromancy", [C, P, D, R, A], { role: "heal" }),
  S_("sending", "Sending", 3, "evocation", [B, C, W, A]),
  S_("sleet-storm", "Sleet Storm", 3, "conjuration", [D, S, W], { conc: true, role: "control", build: saveCond("dex", "prone", 1, { who: "area" }) }),
  S_("slow", "Slow", 3, "transmutation", [S, W, A], { conc: true, role: "control", build: (c) => [{ type: "target", who: { who: "chosenEnemies", upTo: 6 }, effects: [{ type: "save", ability: "wis", dc: c.dc, onFail: [{ type: "applyEffect", name: "slow", durationRounds: 10, mods: { acBonus: -2, attackAdvantage: "dis", noReactions: true }, saveEnds: { ability: "wis", dc: c.dc, at: "endOfTurn" } }] }] }] }),
  S_("speak-with-dead", "Speak with Dead", 3, "necromancy", [B, C, W], {}),
  S_("speak-with-plants", "Speak with Plants", 3, "transmutation", [B, D, R]),
  S_("spirit-guardians", "Spirit Guardians", 3, "conjuration", [C], { conc: true, role: "control", max: 9, build: (c) => { const d = 3 + Math.max(0, c.slotLevel - 3); return [{ type: "target", who: { who: "eachEnemy" }, effects: [{ type: "save", ability: "wis", dc: c.dc, onFail: [{ type: "damage", amount: `${d}d8`, damageType: "radiant" }], onSuccess: [{ type: "damage", amount: `${d}d8`, damageType: "radiant", half: true }] }, { type: "applyEffect", name: "spirit-guardians", durationRounds: 10, tick: [{ type: "damage", amount: `${d}d8`, damageType: "radiant", half: true }] }] }]; } }),
  S_("stinking-cloud", "Stinking Cloud", 3, "conjuration", [B, S, W], { conc: true, role: "control", build: saveCond("con", "incapacitated", 1, { who: "area", saveEnds: false }) }),
  S_("tongues", "Tongues", 3, "divination", [B, C, S, W, K]),
  S_("vampiric-touch", "Vampiric Touch", 3, "necromancy", [S, W, K], { conc: true, role: "damage", max: 9, build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "attack", bonus: c.toHit, onHit: [{ type: "damage", amount: `${3 + Math.max(0, c.slotLevel - 3)}d6`, damageType: "necrotic" }] }] }] }),
  S_("water-breathing", "Water Breathing", 3, "transmutation", [D, R, S, W, A], { rit: true }),
  S_("water-walk", "Water Walk", 3, "transmutation", [C, D, R, S, A], { rit: true }),
  S_("wind-wall", "Wind Wall", 3, "evocation", [D, R], { conc: true }),
  S_("blinding-smite", "Blinding Smite", 3, "evocation", [P], { ct: "bonus", conc: true, role: "buff", build: effect("blinding-smite", {}, { who: "self" }) }),
  S_("conjure-barrage", "Conjure Barrage", 3, "conjuration", [R], { role: "damage", build: saveDmg(3, "dex", 3, 8, "piercing", 0, { who: "area", shape: "cone", size: 60 }) }),
  S_("crusaders-mantle", "Crusader's Mantle", 3, "evocation", [P], { conc: true, role: "buff", build: effect("crusaders-mantle", {}, { who: "eachAlly" }) }),
  S_("elemental-weapon", "Elemental Weapon", 3, "transmutation", [P, R], { conc: true, role: "buff", build: effect("elemental-weapon", {}, { who: "self" }) }),
  S_("hunger-of-hadar", "Hunger of Hadar", 3, "conjuration", [K], { conc: true, role: "control", build: () => [{ type: "target", who: { who: "area", shape: "sphere", size: 10 }, effects: [{ type: "applyEffect", name: "hunger-of-hadar", durationRounds: 10, tick: [{ type: "damage", amount: "2d6", damageType: "cold" }] }] }] }),
  S_("leomunds-tiny-hut", "Leomund's Tiny Hut", 3, "evocation", [B, W], { rit: true }),
  S_("lightning-arrow", "Lightning Arrow", 3, "transmutation", [R], { ct: "bonus", conc: true, role: "damage", max: 9, build: atk(3, 4, 8, "lightning", 1) }),

  // ─────────────────────────────── level 4 ────────────────────────────────
  S_("arcane-eye", "Arcane Eye", 4, "divination", [W, A], { conc: true }),
  S_("banishment", "Banishment", 4, "abjuration", [C, P, S, W, K], { conc: true, role: "control", max: 9, build: saveCond("cha", "incapacitated", 10, { saveEnds: false, perSlotTargets: 1, targetsAtLevel: 4, spellLevel: 4 }) }),
  S_("blight", "Blight", 4, "necromancy", [D, S, W, K], { role: "damage", max: 9, build: saveDmg(4, "con", 8, 8, "necrotic", 1, { who: "aiChoice" }) }),
  S_("compulsion", "Compulsion", 4, "enchantment", [B], { conc: true, role: "control", build: saveCond("wis", "charmed", 10, { who: "area", saveEnds: true }) }),
  S_("confusion", "Confusion", 4, "enchantment", [B, D, S, W], { conc: true, role: "control", max: 9, build: (c) => [{ type: "target", who: { who: "chosenEnemies", upTo: 3 + Math.max(0, c.slotLevel - 4) }, effects: [{ type: "save", ability: "wis", dc: c.dc, onFail: [{ type: "applyCondition", condition: "incapacitated", durationRounds: 10, saveEnds: { ability: "wis", dc: c.dc, at: "endOfTurn" } }] }] }] }),
  S_("conjure-minor-elementals", "Conjure Minor Elementals", 4, "conjuration", [D, W], { conc: true, role: "summon", build: conjure("fire-elemental", "2", 4) }),
  S_("conjure-woodland-beings", "Conjure Woodland Beings", 4, "conjuration", [D, R], { conc: true, role: "summon", build: conjure("wolf", "2", 6) }),
  S_("control-water", "Control Water", 4, "transmutation", [C, D, W], { conc: true }),
  S_("death-ward", "Death Ward", 4, "abjuration", [C, P], { role: "defense", build: effect("death-ward", {}, { who: "self" }) }),
  S_("dimension-door", "Dimension Door", 4, "conjuration", [B, S, W, K], { role: "defense", build: () => [{ type: "move", kind: "teleportSelf", distance: 100 }] }),
  S_("divination", "Divination", 4, "divination", [C], { rit: true }),
  S_("dominate-beast", "Dominate Beast", 4, "enchantment", [D, S], { conc: true, role: "control", build: saveCond("wis", "charmed", 10, { saveEnds: true }) }),
  S_("fabricate", "Fabricate", 4, "transmutation", [W, A]),
  S_("fire-shield", "Fire Shield", 4, "evocation", [S, W], { role: "defense", build: effect("fire-shield", { damageTakenMultiplier: 0.6 }, { who: "self" }) }),
  S_("freedom-of-movement", "Freedom of Movement", 4, "abjuration", [B, C, D, R, A], { role: "defense", build: effect("freedom-of-movement", { saveAdvantage: "adv" }, { who: "self" }) }),
  S_("giant-insect", "Giant Insect", 4, "transmutation", [D], { conc: true, role: "summon", build: conjure("wolf", "3", 4) }),
  S_("greater-invisibility", "Greater Invisibility", 4, "illusion", [B, S, W], { conc: true, role: "buff", build: effect("greater-invisibility", { attackAdvantage: "adv", attacksAgainstItAdvantage: "dis" }, { who: "self" }) }),
  S_("guardian-of-faith", "Guardian of Faith", 4, "conjuration", [C], { role: "damage", build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "save", ability: "dex", dc: c.dc, onFail: [{ type: "damage", amount: "20", damageType: "radiant" }] }] }] }),
  S_("hallucinatory-terrain", "Hallucinatory Terrain", 4, "illusion", [B, D, W, K]),
  S_("ice-storm", "Ice Storm", 4, "evocation", [D, S, W], { role: "damage", max: 9, build: (c) => [{ type: "target", who: { who: "area", shape: "sphere", size: 20 }, effects: [{ type: "save", ability: "dex", dc: c.dc, onFail: [{ type: "damage", amount: "2d8", damageType: "bludgeoning" }, { type: "damage", amount: `${4 + Math.max(0, c.slotLevel - 4)}d6`, damageType: "cold" }], onSuccess: [{ type: "damage", amount: "2d8", damageType: "bludgeoning", half: true }, { type: "damage", amount: `${4 + Math.max(0, c.slotLevel - 4)}d6`, damageType: "cold", half: true }] }] }] }),
  S_("locate-creature", "Locate Creature", 4, "divination", [B, C, D, P, R, W, A], { conc: true }),
  S_("phantasmal-killer", "Phantasmal Killer", 4, "illusion", [W], { conc: true, role: "control", max: 9, build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "save", ability: "wis", dc: c.dc, onFail: [{ type: "applyCondition", condition: "frightened", durationRounds: 10, saveEnds: { ability: "wis", dc: c.dc, at: "endOfTurn" } }, { type: "applyEffect", name: "phantasmal-killer", durationRounds: 10, mods: {}, tick: [{ type: "damage", amount: `${4 + Math.max(0, c.slotLevel - 4)}d10`, damageType: "psychic" }], saveEnds: { ability: "wis", dc: c.dc, at: "endOfTurn" } }] }] }] }),
  S_("polymorph", "Polymorph", 4, "transmutation", [B, D, S, W], { conc: true, role: "control", build: saveCond("wis", "incapacitated", 10, { saveEnds: false }) }),
  S_("private-sanctum", "Private Sanctum", 4, "abjuration", [W, A]),
  S_("resilient-sphere", "Resilient Sphere", 4, "evocation", [W, A], { conc: true, role: "control", build: saveCond("dex", "restrained", 10, { saveEnds: false }) }),
  S_("stone-shape", "Stone Shape", 4, "transmutation", [C, D, W, A]),
  S_("stoneskin", "Stoneskin", 4, "abjuration", [D, R, S, W], { conc: true, role: "defense", build: effect("stoneskin", { damageTakenMultiplier: 0.5 }, { who: "self" }) }),
  S_("wall-of-fire", "Wall of Fire", 4, "evocation", [D, S, W], { conc: true, role: "damage", max: 9, build: (c) => [{ type: "target", who: { who: "eachEnemy" }, effects: [{ type: "save", ability: "dex", dc: c.dc, onFail: [{ type: "damage", amount: `${5 + Math.max(0, c.slotLevel - 4)}d8`, damageType: "fire" }], onSuccess: [] }] }] }),
  S_("aura-of-life", "Aura of Life", 4, "abjuration", [P], { conc: true, role: "buff", build: effect("aura-of-life", {}, { who: "eachAlly" }) }),
  S_("aura-of-purity", "Aura of Purity", 4, "abjuration", [P], { conc: true, role: "buff", build: effect("aura-of-purity", { saveAdvantage: "adv" }, { who: "eachAlly" }) }),
  S_("charm-monster", "Charm Monster", 4, "enchantment", [B, D, S, K, W], { role: "control", build: saveCond("wis", "charmed", 10, { who: { who: "aiChoice" } }) }),
  S_("evards-black-tentacles", "Evard's Black Tentacles", 4, "conjuration", [W], { conc: true, role: "control", build: saveCond("dex", "restrained", 10, { who: { who: "area", shape: "cube", size: 20 }, dmg: [3, 6, "bludgeoning"], saveEnds: true }) }),
  S_("grasping-vine", "Grasping Vine", 4, "conjuration", [D, R], { ct: "bonus", conc: true, role: "control", build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "save", ability: "dex", dc: c.dc, onFail: [{ type: "move", kind: "pull", distance: 20 }] }] }] }),
  S_("leomunds-secret-chest", "Leomund's Secret Chest", 4, "conjuration", [W, A]),
  S_("mordenkainens-faithful-hound", "Mordenkainen's Faithful Hound", 4, "conjuration", [W, A], { ct: "bonus", role: "damage", build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "attack", bonus: c.pb + c.spellMod, onHit: [{ type: "damage", amount: "4d8", damageType: "piercing" }] }] }] }),
  S_("staggering-smite", "Staggering Smite", 4, "evocation", [P], { ct: "bonus", conc: true, role: "buff", build: effect("staggering-smite", {}, { who: "self" }) }),
  S_("vitriolic-sphere", "Vitriolic Sphere", 4, "evocation", [S, W], { role: "damage", max: 9, build: (c) => { const now = 10 + Math.max(0, c.slotLevel - 4) * 2; return [{ type: "target", who: { who: "area", shape: "sphere", size: 20 }, effects: [{ type: "save", ability: "dex", dc: c.dc,
    onFail: [{ type: "damage", amount: `${now}d4`, damageType: "acid" }, { type: "applyEffect", name: "vitriolic-sphere", durationRounds: 1, tick: [{ type: "damage", amount: "5d4", damageType: "acid" }] }],
    onSuccess: [{ type: "damage", amount: `${now}d4`, damageType: "acid", half: true }] }] }]; } }),

  // ─────────────────────────────── level 5 ────────────────────────────────
  S_("animate-objects", "Animate Objects", 5, "transmutation", [B, S, W, A], { conc: true, role: "summon", build: conjure("chain-devil", "1", 2) }),
  S_("antilife-shell", "Antilife Shell", 5, "abjuration", [D], { conc: true }),
  S_("awaken", "Awaken", 5, "transmutation", [B, D]),
  S_("banishing-smite", "Banishing Smite", 5, "abjuration", [P], { conc: true, ct: "bonus", role: "buff", build: effect("banishing-smite", {}, { who: "self" }) }),
  S_("cloudkill", "Cloudkill", 5, "conjuration", [S, W], { conc: true, role: "damage", max: 9, build: saveDmg(5, "con", 5, 8, "poison", 1) }),
  S_("commune", "Commune", 5, "divination", [C], { rit: true }),
  S_("commune-with-nature", "Commune with Nature", 5, "divination", [D, R], { rit: true }),
  S_("cone-of-cold", "Cone of Cold", 5, "evocation", [S, W], { role: "damage", max: 9, build: saveDmg(5, "con", 8, 8, "cold", 1, { who: "area", shape: "cone", size: 60 }) }),
  S_("conjure-elemental", "Conjure Elemental", 5, "conjuration", [D, W], { conc: true, role: "summon", build: conjure("fire-elemental", "1", 2) }),
  S_("contact-other-plane", "Contact Other Plane", 5, "divination", [W, K], { rit: true }),
  S_("contagion", "Contagion", 5, "necromancy", [C, D], { role: "control", build: saveCond("con", "poisoned", 10, { saveEnds: false }) }),
  S_("creation", "Creation", 5, "illusion", [S, W]),
  S_("dispel-evil-and-good", "Dispel Evil and Good", 5, "abjuration", [C, P], { conc: true, role: "defense" }),
  S_("dominate-person", "Dominate Person", 5, "enchantment", [B, S, W], { conc: true, role: "control", max: 9, build: saveCond("wis", "charmed", 10, { saveEnds: true }) }),
  S_("dream", "Dream", 5, "illusion", [B, W, K]),
  S_("flame-strike", "Flame Strike", 5, "evocation", [C], { role: "damage", max: 9, build: (c) => [{ type: "target", who: { who: "area", shape: "sphere", size: 10 }, effects: [{ type: "save", ability: "dex", dc: c.dc, onFail: [{ type: "damage", amount: "4d6", damageType: "fire" }, { type: "damage", amount: `${4 + Math.max(0, c.slotLevel - 5)}d6`, damageType: "radiant" }], onSuccess: [{ type: "damage", amount: "4d6", damageType: "fire", half: true }, { type: "damage", amount: `${4 + Math.max(0, c.slotLevel - 5)}d6`, damageType: "radiant", half: true }] }] }] }),
  S_("geas", "Geas", 5, "enchantment", [B, C, D, P, W]),
  S_("greater-restoration", "Greater Restoration", 5, "abjuration", [B, C, D, A], { role: "heal" }),
  S_("hallow", "Hallow", 5, "evocation", [C]),
  S_("hold-monster", "Hold Monster", 5, "enchantment", [B, S, W, K], { conc: true, role: "control", max: 9, build: saveCond("wis", "paralyzed", 10, { saveEnds: true, perSlotTargets: 1, targetsAtLevel: 5, spellLevel: 5 }) }),
  S_("insect-plague", "Insect Plague", 5, "conjuration", [C, D, S], { conc: true, role: "damage", max: 9, build: saveDmg(5, "con", 4, 10, "piercing", 1) }),
  S_("legend-lore", "Legend Lore", 5, "divination", [B, C, W]),
  S_("mass-cure-wounds", "Mass Cure Wounds", 5, "evocation", [B, C, D], { role: "heal", max: 9, build: (c) => [{ type: "target", who: { who: "eachAlly" }, effects: [{ type: "heal", amount: `${3 + Math.max(0, c.slotLevel - 5)}d8+${c.spellMod}` }] }] }),
  S_("mislead", "Mislead", 5, "illusion", [B, W], { conc: true }),
  S_("modify-memory", "Modify Memory", 5, "enchantment", [B, W], { conc: true }),
  S_("passwall", "Passwall", 5, "transmutation", [W]),
  S_("planar-binding", "Planar Binding", 5, "abjuration", [B, C, D, W]),
  S_("raise-dead", "Raise Dead", 5, "necromancy", [B, C, P], { role: "heal" }),
  S_("reincarnate", "Reincarnate", 5, "transmutation", [D]),
  S_("scrying", "Scrying", 5, "divination", [B, C, D, W, K]),
  S_("seeming", "Seeming", 5, "illusion", [B, S, W]),
  S_("swift-quiver", "Swift Quiver", 5, "transmutation", [R], { conc: true, ct: "bonus", role: "buff", build: effect("swift-quiver", {}, { who: "self" }) }),
  S_("telekinesis", "Telekinesis", 5, "transmutation", [S, W], { conc: true, role: "control", build: saveCond("str", "restrained", 1, { saveEnds: false }) }),
  S_("teleportation-circle", "Teleportation Circle", 5, "conjuration", [B, S, W]),
  S_("tree-stride", "Tree Stride", 5, "conjuration", [D, R], { conc: true }),
  S_("wall-of-force", "Wall of Force", 5, "evocation", [W], { conc: true, role: "control", build: saveCond("dex", "restrained", 10, { who: { who: "chosenEnemies", upTo: 2 }, saveEnds: false }) }),
  S_("wall-of-stone", "Wall of Stone", 5, "evocation", [D, S, W, A], { conc: true, role: "control", build: saveCond("dex", "restrained", 10, { who: { who: "chosenEnemies", upTo: 2 }, saveEnds: false }) }),
  S_("bigbys-hand", "Bigby's Hand", 5, "evocation", [W], { conc: true, ct: "bonus", role: "damage", max: 9, build: atk(5, 4, 8, "force", 2) }),
  S_("circle-of-power", "Circle of Power", 5, "abjuration", [P], { conc: true, role: "buff", build: effect("circle-of-power", { saveAdvantage: "adv" }, { who: "eachAlly" }) }),
  S_("conjure-volley", "Conjure Volley", 5, "conjuration", [R], { role: "damage", build: saveDmg(5, "dex", 8, 8, "piercing", 0, { who: "area", shape: "sphere", size: 40 }) }),
  S_("destructive-wave", "Destructive Wave", 5, "evocation", [P], { role: "damage", build: (c) => [{ type: "target", who: { who: "area", shape: "emanation", size: 30 }, effects: [{ type: "save", ability: "con", dc: c.dc,
    onFail: [{ type: "damage", amount: "5d6", damageType: "thunder" }, { type: "damage", amount: "5d6", damageType: "radiant" }, { type: "applyCondition", condition: "prone", durationRounds: 1 }],
    onSuccess: [{ type: "damage", amount: "5d6", damageType: "thunder", half: true }, { type: "damage", amount: "5d6", damageType: "radiant", half: true }] }] }] }),
  S_("rarys-telepathic-bond", "Rary's Telepathic Bond", 5, "divination", [W], { rit: true }),

  // ─────────────────────────────── level 6 ────────────────────────────────
  S_("blade-barrier", "Blade Barrier", 6, "evocation", [C], { conc: true, role: "damage", build: (c) => [{ type: "target", who: { who: "eachEnemy" }, effects: [{ type: "save", ability: "dex", dc: c.dc, onFail: [{ type: "damage", amount: "6d10", damageType: "slashing" }], onSuccess: [{ type: "damage", amount: "6d10", damageType: "slashing", half: true }] }] }] }),
  S_("chain-lightning", "Chain Lightning", 6, "evocation", [S, W], { role: "damage", max: 9, build: (c) => [{ type: "target", who: { who: "chosenEnemies", upTo: 3 + Math.max(0, c.slotLevel - 6) }, effects: [{ type: "save", ability: "dex", dc: c.dc, onFail: [{ type: "damage", amount: "10d8", damageType: "lightning" }], onSuccess: [{ type: "damage", amount: "10d8", damageType: "lightning", half: true }] }] }] }),
  S_("circle-of-death", "Circle of Death", 6, "necromancy", [S, W, K], { role: "damage", max: 9, build: saveDmg(6, "con", 8, 6, "necrotic", 2) }),
  S_("conjure-fey", "Conjure Fey", 6, "conjuration", [D, K], { conc: true, role: "summon", build: conjure("chain-devil", "1", 2) }),
  S_("contingency", "Contingency", 6, "abjuration", [W]),
  S_("create-undead", "Create Undead", 6, "necromancy", [C, W, K], { role: "summon", build: conjure("zombie", "3", 4) }),
  S_("disintegrate", "Disintegrate", 6, "transmutation", [S, W], { role: "damage", max: 9, build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "save", ability: "dex", dc: c.dc, onFail: [{ type: "damage", amount: `${10 + Math.max(0, c.slotLevel - 6) * 3}d6+40`, damageType: "force" }] }] }] }),
  S_("eyebite", "Eyebite", 6, "necromancy", [B, S, W, K], { conc: true, role: "control", build: saveCond("wis", "unconscious", 10, { saveEnds: false }) }),
  S_("find-the-path", "Find the Path", 6, "divination", [B, C, D], { conc: true }),
  S_("flesh-to-stone", "Flesh to Stone", 6, "transmutation", [W, K], { conc: true, role: "control", build: saveCond("con", "petrified", 10, { saveEnds: true }) }),
  S_("forbiddance", "Forbiddance", 6, "abjuration", [C], { rit: true }),
  S_("globe-of-invulnerability", "Globe of Invulnerability", 6, "abjuration", [S, W], { conc: true, role: "defense", build: effect("globe-of-invuln", { damageTakenMultiplier: 0.5 }, { who: "self" }) }),
  S_("guards-and-wards", "Guards and Wards", 6, "abjuration", [B, W]),
  S_("harm", "Harm", 6, "necromancy", [C], { role: "damage", build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "save", ability: "con", dc: c.dc, onFail: [{ type: "damage", amount: "14d6", damageType: "necrotic" }], onSuccess: [{ type: "damage", amount: "14d6", damageType: "necrotic", half: true }] }] }] }),
  S_("heal", "Heal", 6, "evocation", [C, D], { role: "heal", max: 9, build: (c) => [{ type: "target", who: { who: "lowestHpAlly" }, effects: [{ type: "heal", amount: `${70 + Math.max(0, c.slotLevel - 6) * 10}` }] }] }),
  S_("heroes-feast", "Heroes' Feast", 6, "conjuration", [B, C, D], { role: "buff", build: () => [{ type: "target", who: { who: "eachAlly" }, effects: [{ type: "heal", amount: "2d10" }, { type: "applyEffect", name: "heroes-feast", durationRounds: 10, mods: { saveAdvantage: "adv" } }] }] }),
  S_("magic-jar", "Magic Jar", 6, "necromancy", [W]),
  S_("mass-suggestion", "Mass Suggestion", 6, "enchantment", [B, S, W, K], { role: "control", max: 9, build: saveCond("wis", "charmed", 10, { who: { who: "chosenEnemies", upTo: 6 }, saveEnds: false }) }),
  S_("move-earth", "Move Earth", 6, "transmutation", [D, S, W], { conc: true }),
  S_("planar-ally", "Planar Ally", 6, "conjuration", [C]),
  S_("programmed-illusion", "Programmed Illusion", 6, "illusion", [B, W]),
  S_("sunbeam", "Sunbeam", 6, "evocation", [D, S, W], { conc: true, role: "damage", build: (c) => [{ type: "target", who: { who: "area", shape: "line", size: 60 }, effects: [{ type: "save", ability: "con", dc: c.dc, onFail: [{ type: "damage", amount: "6d8", damageType: "radiant" }, { type: "applyCondition", condition: "blinded", durationRounds: 1 }], onSuccess: [{ type: "damage", amount: "6d8", damageType: "radiant", half: true }] }] }] }),
  S_("transport-via-plants", "Transport via Plants", 6, "conjuration", [D]),
  S_("true-seeing", "True Seeing", 6, "divination", [B, C, S, W, K]),
  S_("wall-of-ice", "Wall of Ice", 6, "evocation", [W], { conc: true, role: "damage", build: saveDmg(6, "dex", 10, 6, "cold", 1) }),
  S_("wall-of-thorns", "Wall of Thorns", 6, "conjuration", [D], { conc: true, role: "damage", build: saveDmg(6, "dex", 7, 8, "piercing", 1) }),
  S_("wind-walk", "Wind Walk", 6, "transmutation", [D]),
  S_("word-of-recall", "Word of Recall", 6, "conjuration", [C]),
  S_("arcane-gate", "Arcane Gate", 6, "conjuration", [S, K, W], { conc: true }),
  S_("drawmijs-instant-summons", "Drawmij's Instant Summons", 6, "conjuration", [W], { rit: true }),
  S_("otilukes-freezing-sphere", "Otiluke's Freezing Sphere", 6, "evocation", [S, W], { role: "damage", max: 9, build: saveDmg(6, "con", 10, 6, "cold", 1, { who: "area", shape: "sphere", size: 60 }) }),
  S_("ottos-irresistible-dance", "Otto's Irresistible Dance", 6, "enchantment", [B, W], { conc: true, role: "control", build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "applyEffect", name: "irresistible-dance", durationRounds: 10, mods: { attackAdvantage: "dis", attacksAgainstItAdvantage: "adv", speedZero: true }, saveEnds: { ability: "wis", dc: c.dc, at: "endOfTurn" } }] }] }),

  // ─────────────────────────────── level 7 ────────────────────────────────
  S_("conjure-celestial", "Conjure Celestial", 7, "conjuration", [C], { conc: true, role: "summon", build: conjure("fire-elemental", "1", 1) }),
  S_("delayed-blast-fireball", "Delayed Blast Fireball", 7, "evocation", [S, W], { conc: true, role: "damage", max: 9, build: saveDmg(7, "dex", 12, 6, "fire", 1) }),
  S_("divine-word", "Divine Word", 7, "evocation", [C], { role: "control", build: saveCond("cha", "stunned", 1, { who: { who: "chosenEnemies", upTo: 4 }, saveEnds: false }) }),
  S_("etherealness", "Etherealness", 7, "transmutation", [B, C, S, W, K]),
  S_("finger-of-death", "Finger of Death", 7, "necromancy", [S, W, K], { role: "damage", build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "save", ability: "con", dc: c.dc, onFail: [{ type: "damage", amount: "7d8+30", damageType: "necrotic" }], onSuccess: [{ type: "damage", amount: "7d8+30", damageType: "necrotic", half: true }] }] }] }),
  S_("fire-storm", "Fire Storm", 7, "evocation", [C, D, S], { role: "damage", max: 9, build: saveDmg(7, "dex", 7, 10, "fire", 1) }),
  S_("forcecage", "Forcecage", 7, "evocation", [B, W, K], { role: "control", build: saveCond("cha", "restrained", 10, { who: { who: "chosenEnemies", upTo: 2 }, saveEnds: false }) }),
  S_("mirage-arcane", "Mirage Arcane", 7, "illusion", [B, D, W]),
  S_("mordenkainens-magnificent-mansion", "Mordenkainen's Magnificent Mansion", 7, "conjuration", [B, W]),
  S_("mordenkainens-sword", "Mordenkainen's Sword", 7, "evocation", [B, W], { conc: true, role: "damage", build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "damage", amount: `3d10+${c.spellMod}`, damageType: "force" }] }] }),
  S_("plane-shift", "Plane Shift", 7, "conjuration", [C, D, S, W, K]),
  S_("prismatic-spray", "Prismatic Spray", 7, "evocation", [S, W], { role: "damage", build: (c) => [{ type: "target", who: { who: "area", shape: "cone", size: 60 }, effects: [{ type: "save", ability: "dex", dc: c.dc, onFail: [{ type: "damage", amount: "10d6", damageType: "fire" }], onSuccess: [{ type: "damage", amount: "10d6", damageType: "fire", half: true }] }] }] }),
  S_("project-image", "Project Image", 7, "illusion", [B, W], { conc: true }),
  S_("regenerate", "Regenerate", 7, "transmutation", [B, C, D], { role: "heal", build: () => [{ type: "target", who: { who: "lowestHpAlly" }, effects: [{ type: "heal", amount: "4d8+15" }] }] }),
  S_("resurrection", "Resurrection", 7, "necromancy", [B, C], { role: "heal" }),
  S_("reverse-gravity", "Reverse Gravity", 7, "transmutation", [D, S, W], { conc: true, role: "control", build: saveCond("dex", "restrained", 1, { who: "area", saveEnds: false }) }),
  S_("sequester", "Sequester", 7, "transmutation", [W]),
  S_("simulacrum", "Simulacrum", 7, "illusion", [W]),
  S_("symbol", "Symbol", 7, "abjuration", [B, C, W]),
  S_("teleport", "Teleport", 7, "conjuration", [B, S, W]),

  // ─────────────────────────────── level 8 ────────────────────────────────
  S_("animal-shapes", "Animal Shapes", 8, "transmutation", [D], { conc: true }),
  S_("antimagic-field", "Antimagic Field", 8, "abjuration", [C, W], { conc: true, role: "defense" }),
  S_("antipathy-sympathy", "Antipathy/Sympathy", 8, "enchantment", [D, W]),
  S_("clone", "Clone", 8, "necromancy", [W]),
  S_("control-weather", "Control Weather", 8, "transmutation", [C, D, W], { conc: true }),
  S_("demiplane", "Demiplane", 8, "conjuration", [W, K]),
  S_("dominate-monster", "Dominate Monster", 8, "enchantment", [B, S, W, K], { conc: true, role: "control", max: 9, build: saveCond("wis", "charmed", 10, { saveEnds: true }) }),
  S_("earthquake", "Earthquake", 8, "evocation", [C, D, S], { conc: true, role: "control", build: saveCond("dex", "prone", 1, { who: "area", dmg: [0, 0, "bludgeoning"], saveEnds: false }) }),
  S_("feeblemind", "Feeblemind", 8, "enchantment", [B, D, S, W, K], { role: "control", build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "save", ability: "int", dc: c.dc, onFail: [{ type: "damage", amount: "4d6", damageType: "psychic" }, { type: "applyEffect", name: "feeblemind", durationRounds: 40, mods: { attackAdvantage: "dis" }, saveEnds: { ability: "int", dc: c.dc, at: "endOfTurn" } }, { type: "applyCondition", condition: "incapacitated", durationRounds: 40, saveEnds: { ability: "int", dc: c.dc, at: "endOfTurn" } }], onSuccess: [{ type: "damage", amount: "4d6", damageType: "psychic", half: true }] }] }] }),
  S_("glibness", "Glibness", 8, "transmutation", [B, K]),
  S_("holy-aura", "Holy Aura", 8, "abjuration", [C], { conc: true, role: "buff", build: effect("holy-aura", { saveAdvantage: "adv", attacksAgainstItAdvantage: "dis" }, { who: "eachAlly" }) }),
  S_("incendiary-cloud", "Incendiary Cloud", 8, "conjuration", [S, W], { conc: true, role: "damage", max: 9, build: saveDmg(8, "dex", 10, 8, "fire", 1) }),
  S_("maze", "Maze", 8, "conjuration", [W], { conc: true, role: "control", build: saveCond("int", "incapacitated", 10, { saveEnds: false }) }),
  S_("mind-blank", "Mind Blank", 8, "abjuration", [B, W], { role: "defense", build: effect("mind-blank", {}, { who: "self" }) }),
  S_("power-word-stun", "Power Word Stun", 8, "enchantment", [B, S, W, K], { role: "control", build: (c) => [{ type: "target", who: { who: "lowestHpEnemy" }, effects: [{ type: "applyCondition", condition: "stunned", durationRounds: 10, saveEnds: { ability: "con", dc: c.dc, at: "endOfTurn" } }] }] }),
  S_("sunburst", "Sunburst", 8, "evocation", [D, S, W], { role: "damage", build: (c) => [{ type: "target", who: { who: "area", shape: "sphere", size: 60 }, effects: [{ type: "save", ability: "con", dc: c.dc, onFail: [{ type: "damage", amount: "12d6", damageType: "radiant" }, { type: "applyCondition", condition: "blinded", durationRounds: 10, saveEnds: { ability: "con", dc: c.dc, at: "endOfTurn" } }], onSuccess: [{ type: "damage", amount: "12d6", damageType: "radiant", half: true }] }] }] }),
  S_("telepathy", "Telepathy", 8, "evocation", [W]),
  S_("tsunami", "Tsunami", 8, "conjuration", [D], { conc: true, role: "damage", build: saveDmg(8, "str", 6, 10, "bludgeoning", 1) }),

  // ─────────────────────────────── level 9 ────────────────────────────────
  S_("astral-projection", "Astral Projection", 9, "necromancy", [C, W, K]),
  S_("foresight", "Foresight", 9, "divination", [B, D, W, K], { role: "buff", build: effect("foresight", { saveAdvantage: "adv", attackAdvantage: "adv", attacksAgainstItAdvantage: "dis" }, { who: "self", durationRounds: 80 }) }),
  S_("gate", "Gate", 9, "conjuration", [C, S, W]),
  S_("imprisonment", "Imprisonment", 9, "abjuration", [W, K], { role: "control", build: (c) => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "save", ability: "wis", dc: c.dc, onFail: [{ type: "applyCondition", condition: "paralyzed", durationRounds: 100 }] }] }] }),
  S_("mass-heal", "Mass Heal", 9, "evocation", [C], { role: "heal", build: () => [{ type: "target", who: { who: "eachAlly" }, effects: [{ type: "heal", amount: "500" }] }] }),  // 700 HP divided -> tops off a party of 4
  S_("meteor-swarm", "Meteor Swarm", 9, "evocation", [S, W], { role: "damage", build: (c) => [{ type: "target", who: { who: "eachEnemy" }, effects: [{ type: "save", ability: "dex", dc: c.dc, onFail: [{ type: "damage", amount: "20d6", damageType: "fire" }, { type: "damage", amount: "20d6", damageType: "bludgeoning" }], onSuccess: [{ type: "damage", amount: "20d6", damageType: "fire", half: true }, { type: "damage", amount: "20d6", damageType: "bludgeoning", half: true }] }] }] }),
  S_("power-word-heal", "Power Word Heal", 9, "evocation", [B, C], { role: "heal", build: () => [{ type: "target", who: { who: "lowestHpAlly" }, effects: [{ type: "heal", amount: "500" }, { type: "removeEffect", name: "stunned" }, { type: "removeEffect", name: "paralyzed" }, { type: "removeEffect", name: "charmed" }, { type: "removeEffect", name: "frightened" }] }] }),  // full HP + shrug off a lockdown
  S_("power-word-kill", "Power Word Kill", 9, "enchantment", [B, S, W, K], { role: "damage", build: () => [{ type: "target", who: { who: "lowestHpEnemy" }, effects: [{ type: "branch", if: "target.hp <= 100", then: [{ type: "damage", amount: "300", damageType: "psychic" }], else: [{ type: "damage", amount: "8d8", damageType: "psychic" }] }] }] }),
  S_("prismatic-wall", "Prismatic Wall", 9, "abjuration", [B, W]),
  S_("psychic-scream", "Psychic Scream", 9, "enchantment", [B, S, W, K], { role: "control", build: (c) => [{ type: "target", who: { who: "chosenEnemies", upTo: 4 }, effects: [{ type: "save", ability: "int", dc: c.dc, onFail: [{ type: "damage", amount: "14d6", damageType: "psychic" }, { type: "applyCondition", condition: "stunned", durationRounds: 10, saveEnds: { ability: "int", dc: c.dc, at: "endOfTurn" } }], onSuccess: [{ type: "damage", amount: "14d6", damageType: "psychic", half: true }] }] }] }),
  S_("shapechange", "Shapechange", 9, "transmutation", [D, W], { conc: true }),
  S_("storm-of-vengeance", "Storm of Vengeance", 9, "conjuration", [D], { conc: true, role: "damage", build: (c) => [{ type: "target", who: { who: "eachEnemy" }, effects: [{ type: "save", ability: "con", dc: c.dc, onFail: [{ type: "damage", amount: "2d6", damageType: "thunder" }, { type: "applyCondition", condition: "deafened", durationRounds: 10 }], onSuccess: [] }] }] }),
  S_("time-stop", "Time Stop", 9, "transmutation", [S, W], { role: "buff", build: effect("time-stop", {}, { who: "self", durationRounds: 2 }) }),
  S_("true-polymorph", "True Polymorph", 9, "transmutation", [B, D, W, K], { conc: true, role: "control", build: saveCond("wis", "incapacitated", 100, { saveEnds: false }) }),
  S_("true-resurrection", "True Resurrection", 9, "necromancy", [C, D], { role: "heal" }),
  S_("weird", "Weird", 9, "illusion", [W], { conc: true, role: "control", build: (c) => [{ type: "target", who: { who: "chosenEnemies", upTo: 4 }, effects: [{ type: "save", ability: "wis", dc: c.dc, onFail: [{ type: "applyCondition", condition: "frightened", durationRounds: 10, saveEnds: { ability: "wis", dc: c.dc, at: "endOfTurn" } }, { type: "applyEffect", name: "weird", durationRounds: 10, mods: {}, tick: [{ type: "damage", amount: "4d10", damageType: "psychic" }], saveEnds: { ability: "wis", dc: c.dc, at: "endOfTurn" } }] }] }] }),
  S_("wish", "Wish", 9, "conjuration", [S, W], { role: "damage", build: () => [{ type: "target", who: { who: "aiChoice" }, effects: [{ type: "damage", amount: "10d6", damageType: "force" }] }] }),
];

export const SPELLS_BY_ID: Record<string, Spell> = Object.fromEntries(SPELLS.map((s) => [s.id, s]));

export function spellsForClass(cls: SpellClass): Spell[] {
  return SPELLS.filter((s) => s.classes.includes(cls));
}
